export const ADD_MODULE = 'ADD_MODULE';
export const CONNECT_MODULES = 'CONNECT_MODULES';
export const DISCONNECT_MODULE = 'DISCONNECT_MODULE';
export const REGISTER_INPUTS = 'REGISTER_INPUTS';
export const REGISTER_OUTPUTS = 'REGISTER_OUTPUTS';
export const MOVE_MODULE = 'MOVE_MODULE';
export const REMOVE_MODULE = 'REMOVE_MODULE';
export const REMOVE_ALL_MODULES = 'REMOVE_ALL_MODULES';

export const SET_STARTING_PORT = 'SET_STARTING_PORT';
export const UNSET_STARTING_PORT = 'UNSET_STARTING_PORT';

export const ADD_CABLE = 'ADD_CABLE';
export const MODIFY_CABLE = 'MODIFY_CABLE';
export const REMOVE_CABLE = 'REMOVE_CABLE';

export const LOAD_PRESET_START = 'LOAD_PRESET_START';
export const LOAD_PRESET_FINISH = 'LOAD_PRESET_FINISH';