export const ADD_MODULE = 'ADD_MODULE';
export const CONNECT_MODULES = 'CONNECT_MODULES';
export const DISCONNECT_MODULE = 'DISCONNECT_MODULE';
export const REGISTER_INPUTS = 'REGISTER_INPUTS';
export const REGISTER_OUTPUTS = 'REGISTER_OUTPUTS';