export const ADD_MODULE = 'ADD_MODULE';
export const CONNECT_MODULES = 'CONNECT_MODULES';
export const DISCONNECT_MODULE = 'DISCONNECT_MODULE';
export const REGISTER_INPUTS = 'REGISTER_INPUTS';
export const REGISTER_OUTPUTS = 'REGISTER_OUTPUTS';

export const SET_STARTING_PORT = 'SET_STARTING_PORT';
export const UNSET_STARTING_PORT = 'UNSET_STARTING_PORT';

export const ADD_CABLE = 'ADD_CABLE';
export const MODIFY_CABLE = 'MODIFY_CABLE';
export const REMOVE_CABLE = 'REMOVE_CABLE';